version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: utilityservices
      POSTGRES_USER: utilityuser 
      POSTGRES_PASSWORD: my#123pass
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data

# volumes:
#   db-data:
